from .base import BASE_PROMPT
from .analysis import EXPENSE_ANALYSIS_PROMPT, CATEGORY_ANALYSIS_PROMPT, ANOMALY_ANALYSIS_PROMPT
from .generation import BUDGET_GENERATION_PROMPT, UI_INSIGHTS_PROMPT
from .prediction import EXPENSE_FORECAST_PROMPT
from .qa import QA_PROMPT
from .scoring import FINANCIAL_SCORE_PROMPT

__all__ = [
    "BASE_PROMPT",
    "EXPENSE_ANALYSIS_PROMPT",
    "CATEGORY_ANALYSIS_PROMPT",
    "ANOMALY_ANALYSIS_PROMPT",
    "EXPENSE_FORECAST_PROMPT",
    "BUDGET_GENERATION_PROMPT",
    "UI_INSIGHTS_PROMPT",
    "QA_PROMPT",
    "FINANCIAL_SCORE_PROMPT",
]

